name: Docker Image Build

on:
  push:
    tags:
      - '**'
      - '!*docker*'

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, other]
        include:
          - branch: master
            tags: "\
              latest,priority=900\n\
               4.2.2,priority=700\n\
                 4.0,priority=500\n\
                   4,priority=300\n\
              stable,priority=100"
          - branch: other
            tags: type=raw,value=pages

    steps:
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Set Metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: rockstorm/git-server
         tags: ${{ matrix.tags }}|
          
     - name: Echo Results
       run: |
         echo "${{ matrix.branch }}"
         echo "${{ steps.meta.outputs.tags }}"
