name: Docker Image Build

on:
  push:
    tags:
      - '**'
      - '!*docker*'

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, other]
        include:
          - branch: master
            tags: |
              type=raw,priority=900,value=latest
              type=raw,priority=700,value=4.2.2
              type=raw,priority=500,value=4.0
              type=raw,priority=300,value=4
              type=raw,priority=100,value=stable
              type=raw,enable=false,value=-

    steps:
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Set Metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: rockstorm/git-server
         tags: ${{ matrix.tags }}|
          
     - name: Echo Results
       run: |
         echo "${{ matrix.branch }}"
         echo "${{ steps.meta.outputs.tags }}"
