name: Build Windows Executable

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        # supported architecture: [x64, x86]
        architecture: [x86, x64]
        # supported versions: ['3.8', '3.9', '3.10', '3.11']
        # for x86 only Python 3.9 to 3.11 is supported
        python-version: ['3.10']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configuration for releases
      if: ${{ github.event_name == 'release' }}
      run: |
        "EXE_NAME=${{ github.ref_name }}" >> $env:GITHUB_ENV

    - name: Configuration for pushes
      if: ${{ github.event_name == 'push' }}
      run: |
        "EXE_NAME=printrun-nightly" >> $env:GITHUB_ENV

    - name: Configuration for pull requests
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        "EXE_NAME=printrun-test" >> $env:GITHUB_ENV

    - name: Upload artifacts for inspection
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.EXE_NAME }}_windows_${{ matrix.architecture }}_py${{ matrix.python-version }}
        path: |
            test.txt

  upload_release_assets:
    needs: [build]
    if: github.event_name == 'release' && github.event.action == 'published'
    uses: rockstorm101/test-actions/.github/workflows/upload-assets.yml@main
