name: Docker Image Build

on:
  # push:
  #   tags:
  #     - '**'
  #     - '!*docker*'

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: [latest, pages]  # "latest" Jekyll vs. GitHub "pages"
        variant: [jekyll, builder, minimal]
        include:
          - version: latest
            tags: |
              type=semver,pattern={{version}},priority=700
              type=semver,pattern={{major}}.{{minor}},priority=500
              type=semver,pattern={{major}},priority=300
          - version: pages
            tags: |
              pages
          # Add suffixes for variants
          - variant: builder
            suffix: -builder
          - variant: minimal
            suffix: -minimal
        exclude:
          - version: pages
            variant: builder
          - version: pages
            variant: minimal

    steps:
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Set Metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: rockstorm/jekyll
         flavor: |
           latest=${{  matrix.version == 'latest' &&  matrix.variant == 'jekyll' }}
           suffix=${{ matrix.suffix }}
         tags: ${{ matrix.tags }}
          
     - name: Echo Results
       run: |
         echo "Context: ./repos/${{ matrix.variant }}/cache/${{ matrix.version }}"
         echo "Tags: ${{ steps.meta.outputs.tags }}"
