name: Docker Image Build

on:
  push:
    tags:
      - '**'
      - '!*docker*'

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: [latest]  # "latest" Jekyll vs. GitHub "pages"
        variant: [builder, minimal]
        latest: [false]  # whether to produce 'latest' tag or not
        include:
          # Add standard or 'jekyll' variant 
          - version: latest
            variant: jekyll
            latest: true
          # Set up tags for all "latest" Jekyll versions
          - version: latest
            tags: |
              type=semver,pattern={{version}},priority=700
              type=semver,pattern={{major}}.{{minor}},priority=500
              type=semver,pattern={{major}},priority=300
          # Add GitHub Pages version
          - version: pages
            variant: jekyll
            latest: false
            tags: |
              pages
          # Add suffixes for variants
          - variant: builder
            suffix: -builder
          - variant: minimal
            suffix: -minimal

    steps:
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Set Metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: rockstorm/jekyll
         flavor: |
           latest=${{ matrix.latest }}
           suffix=${{ matrix.suffix }}
         tags: ${{ matrix.tags }}
          
     - name: Echo Results
       run: |
         echo "Context: ./repos/${{ matrix.variant }}/cache/${{ matrix.version }}"
         echo "Tags: ${{ steps.meta.outputs.tags }}"
