name: Docker Image Build

on:
  push:
    tags:
      - '**'
      - '!*docker*'

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Set Metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: rockstorm/git-server
         tags: |
           type=semver,pattern={{raw}},value=0.1.0+b2
           type=semver,pattern={{version}},value=0.1.0+b2
           type=semver,pattern={{major}}.{{minor}},value=0.1.0+b2
          
     - name: Echo Results
       run: |
         echo "${{ matrix.branch }}"
         echo "${{ steps.meta.outputs.tags }}"
