name: Docker Image Build

on:
  push:
    tags:
      - '**'
      - '!*docker*'

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        variant: [jekyll, builder, minimal]
        main_tag: [latest]
        include:
          - variant: builder
            suffix: -builder
          - variant: minimal
            suffix: -minimal
          - main_tag: latest
            tags: |
              type=semver,pattern={{raw}},priority=700
              type=semver,pattern={{major}}.{{minor}},priority=500
              type=semver,pattern={{major}},priority=300
          - main_tag: latest
            variant: jekyll
            latest: true
          - main_tag: pages
            variant: jekyll
            tags: |
              pages,suffix={{ matrix.suffix }}

    steps:
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Set Metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: rockstorm/jekyll
         flavor: |
           latest=${{ matrix.latest }}
           suffix=${{ matrix.suffix }}
         tags: ${{ matrix.tags }}
          
     - name: Echo Results
       run: |
         echo "Context: ./repos/${{ matrix.variant }}/cache/${{ matrix.main_tag }}"
         echo "Tags: ${{ steps.meta.outputs.tags }}"
