name: Upload Assets to Releases

on:
  workflow_call:

jobs:
  upload_release_assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      actions: read
      issues: read
      packages: write
      pull-requests: read
      repository-projects: read
      statuses: read
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: printrun-*
          path: upload
          merge-multiple: false

      - name: Upload assets
        run: |
          ls ./upload/
          echo "Upload might happen here. Token: ${{ github.token }}"
